version: '3'
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile
    command: go run main.go
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    ports:
      - 8080:8080
    depends_on:
      - "db"

  db:
    container_name: davida_db
    platform: linux/x86_64 #m1
    image: mysql@sha256:d8e4032005f53a774f2361281ebf61fa3d7635d5dacf9c58bc54e823ddcf9f1d #m1
    # image: mysql:5.7.22
    environment:
      TZ: Asia/Tokyo
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: "adminpasspass"
      MYSQL_ROOT_PASSWORD: ""
    ports:
      - "6606:3306"
    volumes:
      - ./docker/mysql_data:/var/lib/mysql:delegated
volumes:
  db-data:
